### ISSUE TITLE
request: ultrawide (21:9) color test video

### ISSUE THREAD

**Issue by jmt-gh** [dmadison/Adalight-FastLED#14]
Any chance you could add a version of the [Color Test](https://www.youtube.com/watch?v=8u4UzzJZAUg) video that is native 21:9 aspect ratio? I've got everything up and working, but would love to have a nice 21:9 demo video to showcase everything.

PS: Thanks for all the work you've done! FastLED seems to fix a few bugs I was running into with a different arduino implementation, and your write up on LED calibration was amazing!

**Comment by dmadison** [comment]
Thanks! I'm not working on this at the moment, and unfortunately I don't think I set up the render files to work with 21:9 easily. Although you should be able to download the video from YouTube and crop it. VLC will even allow you to crop it on the fly without editing.

Closing this issue, as there's not an issue with the code.
