### ISSUE TITLE
Script is out of the box not compatible with 4-wire LED strips

### ISSUE THREAD

**Issue by Landcross** [dmadison/Adalight-FastLED#16]
Hi there,

Based on your recent recommendation I bought an APA102 ledstrip instead of a WS2812b. At first I tested the strip with some random examples, worked great. Then I wanted to test it as an ambilight strip before I would cut it and start soldering and gluing it to the back of my monitor.

I wanted to load your script onto my arduino, but it threw an error. My APA102 ledstrip contains a clock and data pin and you need to pass both to FastLED.

So instead of just
`Led_Pin = 6`

You need
`Data_Pin = 6`
`Clock_Pin = 13`

And then pass it to FastLED:
`FastLED.addLeds<LED_TYPE, Data_Pin, Clock_Pin, COLOR_ORDER>(leds, Num_Leds);`

Then the your script seems to work fine with the APA102.

**Comment by dmadison** [comment]
Fixed with #18. Thanks!
